title = "Fn::equals will always return true or false"
verbose_name = "W8003"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["functions", "equals"]
description = '''
Validate Fn::Equals to see if its comparing two strings or two equal items. While this works it may not be intended.

### References:
[Intrinsic Function Reference Conditions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-equals)
'''
