title = "Check if the referenced conditions are defined"
verbose_name = "E8002"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["conditions"]
description = '''
Making sure the used conditions are actually defined in the Conditions section

### References:
[Conditions Section Structure](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html)
'''
