title = "Tojsonstring validation of parameters"
verbose_name = "E1031"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["functions", "toJsonString"]
description = '''
Making sure Fn::ToJsonString is configured correctly

### References:
[Intrinsic Function Reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)
'''
