title = "Output name limit"
verbose_name = "I6011"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["outputs", "limits"]
description = '''
Check the size of Output names in the template is approaching the upper limit

### References:
[CloudFormation Limits](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)
'''
