title = "Output limit"
verbose_name = "I6010"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["outputs", "limits"]
description = '''
Check the number of Outputs in the template is approaching the upper limit

### References:
[CloudFormation Limits](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)
'''
