title = "Check at least one essential container is specified"
verbose_name = "E3042"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["properties", "ecs", "task", "container", "fargate"]
description = '''
Check that every TaskDefinition specifies at least one essential container

### References:
[Aws Properties Ecs Taskdefinition Containerdefinitions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions.html#cfn-ecs-taskdefinition-containerdefinition-essential)
'''
