title = "Resource ec2 security group ingress properties"
verbose_name = "E2506"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["resources", "ec2", "securitygroup"]
description = '''
See if EC2 Security Group Ingress Properties are set correctly. Check that "SourceSecurityGroupId" or "SourceSecurityGroupName" are  are exclusive and using the type of Ref or GetAtt 

### References:
[Aws Properties Ec2 Security Group Ingress](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-ingress.html)
'''
