title = "Parameter limit"
verbose_name = "I2010"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["parameters", "limits"]
description = '''
Check the number of Parameters in the template is approaching the upper limit

### References:
[CloudFormation Limits](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)
'''
