title = "Mapping name limit"
verbose_name = "I7011"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["mappings", "limits"]
description = '''
Check the size of Mapping names in the template is approaching the upper limit

### References:
[CloudFormation Limits](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)
'''
