title = "Check values of properties for valid refs and getatts"
verbose_name = "E3008"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["resources", "ref", "getatt"]
description = '''
Checks resource properties for Ref and GetAtt values

### References:
[]()
'''
