title = "Outputs have appropriate properties"
verbose_name = "E6001"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["outputs"]
description = '''
Making sure the outputs are properly configured

### References:
[Outputs Section Structure](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html)
'''
