title = "Validate that snapstart is properly configured"
verbose_name = "W2530"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["resources", "lambda"]
description = '''
To properly leverage SnapStart, you must configure both the lambda function and attach a Lambda version resource

### References:
[Snapstart](https://docs.aws.amazon.com/lambda/latest/dg/snapstart.html)
'''
