title = "Codepipeline stage actions"
verbose_name = "E2541"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["resources", "codepipeline"]
description = '''
See if CodePipeline stage actions are set correctly

### References:
[Reference Pipeline Structure](https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#pipeline-requirements)
'''
