title = "Sub validation of parameters"
verbose_name = "E1019"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["functions", "sub"]
description = '''
Making sure the sub function is properly configured

### References:
[Intrinsic Function Reference Sub](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html)
'''
