title = "Mapping attribute limit"
verbose_name = "I7012"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["mappings", "limits"]
description = '''
Check if the amount of Mapping attributes in the template is approaching the upper limit

### References:
[CloudFormation Limits](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)
'''
