title = "Check if a string has between min and max number of values specified"
verbose_name = "E3033"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["resources", "property", "string", "size"]
description = '''
Check strings for its length between the minimum and maximum

### References:
[CloudFormation Resource Specification](https://github.com/awslabs/cfn-python-lint/blob/main/docs/cfn-resource-specification.md#allowedpattern)
'''
