title = "Check fn::and structure for validity"
verbose_name = "E8004"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["functions", "and"]
description = '''
Check Fn::And is a list of two elements

### References:
[Intrinsic Function Reference Conditions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-reference-conditions-and)
'''
