title = "Importvalue validation of parameters"
verbose_name = "E1016"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["functions", "importvalue"]
description = '''
Making sure the ImportValue function is properly configured

### References:
[Intrinsic Function Reference Importvalue](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html)
'''
