title = "Codepipeline stages"
verbose_name = "E2540"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["properties", "codepipeline"]
description = '''
See if CodePipeline stages are set correctly

### References:
[Reference Pipeline Structure](https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#pipeline-requirements)
'''
