title = "Use sub instead of join"
verbose_name = "I1022"
severity = "major"
category = "antipattern"
dimension = "hygiene"
weight = 70
tags = ["functions", "sub", "join"]
description = '''
Prefer a sub instead of Join when using a join delimiter that is empty

### References:
[Intrinsic Function Reference Sub](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html)
'''
