title = "Check if a json object is within size limits"
verbose_name = "E3502"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["resources", "limits", "json"]
description = '''
Validate properties that are JSON values so that their length is within the limits

### References:
[CloudFormation Limits](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html)
'''
