title = "Check deletionpolicy values for resources"
verbose_name = "E3035"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
tags = ["resources", "deletionpolicy"]
description = '''
Check that the DeletionPolicy values are valid

### References:
[Aws Attribute Deletionpolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html)
'''
