title = "Unnecessary raw string"
weight = 70
severity = "major"
category = "antipattern"
dimension = "hygiene"
verbose_name = "unnecessary_raw_strings"
description = '''
Use raw string only when needed.

**BAD:**
```dart
var s1 = r'a';
```

**GOOD:**
```dart
var s1 = 'a';
var s2 = r'$a';
var s3 = r'\a';
```
'''
