title = "Use a setter for operations that conceptually change a property"
weight = 70
severity = "major"
category = "antipattern"
dimension = "hygiene"
verbose_name = "use_setters_to_change_properties"
description = '''
**DO** use a setter for operations that conceptually change a property.

**BAD:**
```dart
rectangle.setWidth(3);
button.setVisible(false);
```

**GOOD:**
```dart
rectangle.width = 3;
button.visible = false;
```
'''
