title = "Unnecessary string interpolation"
weight = 70
severity = "major"
category = "antipattern"
dimension = "hygiene"
verbose_name = "unnecessary_string_interpolations"
description = '''
**DON'T** use string interpolation if there's only a string expression in it.

**BAD:**
```dart
String message;
String o = '$message';
```

**GOOD:**
```dart
String message;
String o = message;
```
'''
