title = "Unnecessary new keyword"
weight = 70
severity = "major"
category = "antipattern"
dimension = "hygiene"
verbose_name = "unnecessary_new"
description = '''
**AVOID** new keyword to create instances.

**BAD:**
```dart
class A { A(); }
m(){
  final a = new A();
}
```

**GOOD:**
```dart
class A { A(); }
m(){
  final a = A();
}
```
'''
