title = "Event name must be in CamelCase"
verbose_name = "event-name-camelcase"
severity = "minor"
category = "style"
dimension = "hygiene"
weight = 40
description = """
Event name must be in CamelCase.

<!--more-->

## Learn more
[event-name-camelcase](https://github.com/protofire/solhint/blob/develop/docs/rules/naming/event-name-camelcase.md) on Solhint's documentation.
"""
