title = "Visibility modifier must be first in list of modifiers"
verbose_name = "visibility-modifier-order"
severity = "minor"
category = "style"
weight = 40
description = """
Visibility modifier must be first in list of modifiers.

<!--more-->

## Not Recommended(s)
1. Visibility modifier not placed first
```solidity

      pragma solidity 0.4.4;


      contract A {
        function a() ownable() public payable {}
      }

```

## Recommended
1. Visibility modifier placed first
```solidity

      pragma solidity 0.4.4;


      contract A {
        function a() public ownable() payable {}
      }

```

## Learn more
[visibility-modifier-order](https://github.com/protofire/solhint/blob/develop/docs/rules/order/visibility-modifier-order.md) on Solhint's documentation.
"""
