title = "Modifier name must be in mixedCase"
verbose_name = "modifier-name-mixedcase"
severity = "minor"
category = "style"
dimension = "hygiene"
weight = 40
description = """
Modifier name must be in mixedCase.

<!--more-->

## Learn more
[modifier-name-mixedcase](https://github.com/protofire/solhint/blob/develop/docs/rules/naming/modifier-name-mixedcase.md) on Solhint's documentation.
"""
