title = "Compiler version must satisfy a semver requirement"
verbose_name = "compiler-version"
severity = "critical"
category = "security"
dimension = "security"
weight = 80
description = """
Compiler version must satisfy a semver requirement.

<!--more-->

## Learn more
[compiler-version](https://github.com/protofire/solhint/blob/develop/docs/rules/security/compiler-version.md) on Solhint's documentation.
"""
