title = "Enforces the use of double or simple quotes as configured for string literals. Values must be 'single' or 'double'"
verbose_name = "quotes"
severity = "major"
category = "antipattern"
dimension = "hygiene"
weight = 60
description = """
Enforces the use of double or simple quotes as configured for string literals. Values must be 'single' or 'double'.

<!--more-->

## Bad Practice
1. Configured with single quotes
```solidity

      pragma solidity 0.4.4;


      contract A {
        string private a = "test";
      }

```

2. Configured with double quotes
```solidity

      pragma solidity 0.4.4;


      contract A {
        string private a = 'test';
      }

```

## Recommended
1. Configured with double quotes
```solidity

      pragma solidity 0.4.4;


      contract A {
        string private a = "test";
      }

```

2. Configured with single quotes
```solidity

      pragma solidity 0.4.4;


      contract A {
        string private a = 'test';
      }

```

3. Configured with double quotes
```solidity
string private constant STR = "You shall 'pass' !";
```

4. Configured with single quotes
```solidity
string private constant STR = 'You shall "pass" !';
```

## Learn more
[quotes](https://github.com/protofire/solhint/blob/develop/docs/rules/miscellaneous/quotes.md) on Solhint's documentation.
"""
