title = "Function has cyclomatic complexity `current` but allowed no more than maxcompl"
verbose_name = "code-complexity"
severity = "minor"
category = "antipattern"
dimension = "complexity"
weight = 40
description = """
Function has cyclomatic complexity `current` but allowed no more than maxcompl.

<!--more-->

## Bad Practice
1. High code complexity
```solidity
 if (a > b) {                   
   if (b > c) {                 
     if (c > d) {               
       if (d > e) {             
       } else {                 
       }                        
     }                          
   }                            
 }                              
for (i = 0; i < b; i += 1) { }  
do { d++; } while (b > c);       
while (d > e) { }               
```

## Recommended
1. Low code complexity
```solidity
 if (a > b) {                   
   if (b > c) {                 
     if (c > d) {               
     }                          
   }                            
 }                              
for (i = 0; i < b; i += 1) { }  
do { d++; } while (b > c);       
while (d > e) { }               
```

## Learn more
[code-complexity](https://github.com/protofire/solhint/blob/develop/docs/rules/best-practises/code-complexity.md) on Solhint's documentation.
"""
