title = "Low level calls"
verbose_name = "low-level-calls"
severity = "minor"
category = "antipattern"
dimension = "reliability"
weight = 40
description = """
The use of low-level calls is error-prone. Low-level calls do not check for [code existence](https://solidity.readthedocs.io/en/v0.4.25/control-structures.html#error-handling-assert-require-revert-and-exceptions) or call success.

<!--more-->

## Recommendation
Avoid low-level calls. Check the call success. If the call is meant for a contract, check for code existence.

## Learn more
[low-level-calls](https://github.com/crytic/slither/wiki/Detector-Documentation#low-level-calls) on Slither's wiki.
"""
