title = "Assembly usage"
verbose_name = "assembly"
severity = "minor"
category = "antipattern"
dimension = "reliability"
weight = 40
description = """
The use of assembly is error-prone and should be avoided.

<!--more-->

## Recommendation
Do not use `evm` assembly.

## Learn more
[assembly](https://github.com/crytic/slither/wiki/Detector-Documentation#assembly-usage) on Slither's wiki.
"""
