title = "Mismatching deployment selector and pod template labels"
weight = 70
severity = "major"
category = "antipattern"
dimension = "reliability"
description = """
Indicates when deployment selectors fail to match the pod template labels.

<!--more-->

## Remediation
Confirm that your deployment selector correctly matches the labels in its pod template.

"""
verbose_name = "mismatching-selector"
