title = "Non-SSH services using port 22"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
description = """
Indicates when deployments expose port 22, which is commonly reserved for SSH access.

<!--more-->

## Remediation
Ensure that non-SSH services are not using port 22. Confirm that any actual SSH servers have been vetted.
"""
verbose_name = "ssh-port"
