title = "Missing readiness probe"
weight = 70
severity = "major"
category = "antipattern"
dimension = "reliability"
description = """
Indicates when containers fail to specify a readiness probe.

<!--more-->

## Remediation
Specify a readiness probe in your container. Refer to https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/ for details.

"""
verbose_name = "no-readiness-probe"
