title = "`PodDisruptionBudget` with `maxUnavailable` value preventing disruptions"
weight = 70
severity = "major"
category = "antipattern"
dimension = "reliability"
description = """
Indicates when a PodDisruptionBudget has a maxUnavailable value that will always prevent disruptions of pods created by related deployment-like objects.

<!--more-->

## Remediation
Change the PodDisruptionBudget to have maxUnavailable set to a value greater than 0. Refer to https://kubernetes.io/docs/tasks/run-application/configure-pdb/ for more information.

"""
verbose_name = "pdb-max-unavailable"
