title = "Ingress without associated services"
weight = 70
severity = "major"
category = "antipattern"
dimension = "reliability"
description = """
Indicates when ingress do not have any associated services.

<!--more-->

## Remediation
Confirm that your ingress's backend correctly matches the name and port on one of your services.

"""
verbose_name = "dangling-ingress"
