title = "Resources deployed to default namespace"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
description = """
Indicates when a resource is deployed to the default namespace. CIS Benchmark 5.7.1: Create administrative boundaries between resources using namespaces. CIS Benchmark 5.7.4: The default namespace should not be used.

<!--more-->

## Remediation
Create namespaces for objects in your deployment.
"""
verbose_name = "use-namespace"
