
title = "Startup probe port mismatch"
verbose_name = "startup-port"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
description = """
Indicates when containers have a startup probe to a not exposed port.

<!--more-->

## Remediation
Check which ports you've exposed and ensure they match what you have specified in the startup probe.
"""
