title = "Sharing host's IPC namespace"
weight = 70
severity = "major"
category = "antipattern"
dimension = "reliability"
description = """
Alert on pods/deployment-likes with sharing host's IPC namespace

<!--more-->

## Remediation
Ensure the host's IPC namespace is not shared.

"""
verbose_name = "host-ipc"
