
title = "Missing restart policy"
verbose_name = "restart-policy"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
description = """
Indicates when a deployment-like object does not use a restart policy

<!--more-->

## Remediation
Set up the restart policy for your object to 'Always' or 'OnFailure' to increase the fault tolerance.
"""
