title = "Pods sharing host's network namespace"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
description = """
Alert on pods/deployment-likes with sharing host's network namespace

<!--more-->

## Remediation
Ensure the host's network namespace is not shared.
"""
verbose_name = "host-network"
