
title = "Liveness probe port mismatch"
verbose_name = "liveness-port"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
description = """
Indicates when containers have a liveness probe to a not exposed port.

<!--more-->

## Remediation
Check which ports you've exposed and ensure they match what you have specified in the liveness probe.
"""
