title = "Invalid service account reference"
weight = 70
severity = "major"
category = "antipattern"
dimension = "reliability"
description = """
Indicates when pods reference a service account that is not found.

<!--more-->

## Remediation
Create the missing service account, or refer to an existing service account.

"""
verbose_name = "non-existent-service-account"
