title = "Forbidden service types for exposed services"
weight = 70
severity = "major"
category = "antipattern"
dimension = "reliability"
description = """
Alert on services for forbidden types

<!--more-->

## Remediation
Ensure containers are not exposed through a forbidden service type such as NodePort or LoadBalancer.

"""
verbose_name = "exposed-services"
