
title = "ServiceMonitor selector mismatch"
verbose_name = "dangling-servicemonitor"
severity = "major"
category = "antipattern"
dimension = "reliability"
weight = 70
description = """
Indicates when a service monitor's selectors don't match any service. ServiceMonitors are a custom resource only used by the Prometheus operator (https://prometheus-operator.dev/docs/operator/design/#servicemonitor).

<!--more-->

## Remediation
Check selectors and your services.
"""
