title = "Missing deployment for service"
weight = 70
severity = "major"
category = "antipattern"
dimension = "reliability"
description = """
Indicates when services do not have any associated deployments.

<!--more-->

## Remediation
Confirm that your service's selector correctly matches the labels on one of your deployments.

"""
verbose_name = "dangling-service"
