title = "Missing `dnsConfig` options in deployments"
weight = 70
severity = "major"
category = "antipattern"
dimension = "reliability"
description = """
Alert on deployments that have no specified dnsConfig options

<!--more-->

## Remediation
Specify dnsconfig options in your Pod specification to ensure the expected DNS setting on the Pod. Refer to https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config for details.

"""
verbose_name = "dnsconfig-options"
