title = "Invalid container image"
weight = 70
severity = "major"
category = "antipattern"
dimension = "reliability"
description = """
Indicates when a deployment-like object is running a container with an invalid container image

<!--more-->

## Remediation
Use a container image with a specific tag other than latest.

"""
verbose_name = "latest-tag"
